/** Fallback catalog when WooCommerce returns no nodes — keeps layout reviewable without WP. */
export const DEMO_GRID_PRODUCTS = [
  {
    id: "demo-1",
    name: "The Matcha Glow Bear",
    displayName: "Matcha",
    price: "$79.00",
    rawPrice: "79",
    imageUrl: "/hero-bear.png",
    imageAlt: "Glow bear in gift box",
    swatches: ["Matcha"],
  },
  {
    id: "demo-2",
    name: "The Sakura Glow Bear",
    displayName: "Sakura",
    price: "$79.00",
    rawPrice: "79",
    imageUrl: "/hero-bear.png",
    imageAlt: "Glow bear in gift box",
    swatches: ["Sakura"],
  },
  {
    id: "demo-3",
    name: "The Honey Glow Bear",
    displayName: "Honey",
    price: "$79.00",
    rawPrice: "79",
    imageUrl: "/hero-bear.png",
    imageAlt: "Glow bear in gift box",
    swatches: ["Honey"],
  },
  {
    id: "demo-4",
    name: "The Cloud Glow Bear",
    displayName: "Cloud",
    price: "$79.00",
    rawPrice: "79",
    imageUrl: "/hero-bear.png",
    imageAlt: "Glow bear in gift box",
    swatches: ["Cloud"],
  },
];
